version: '3.8'
services:
    debtbot-bot:
        restart: always
        image: debtbot-bot
        container_name: debtbot-bot
        build:
            context: ./bot
            dockerfile: ./bot.Dockerfile
        tty: true
